name: Manual Trigger Example

on:
  workflow_dispatch:
jobs:
  send_message_to_teams:
      runs-on: windows-latest
      steps:
      - name: Step1
        id: step1
        run: >-
          echo "::set-output name=TESTURL::$(
          '{ "name": "test-name","test-url": "https://github.com"}')"
      - name: step2
        id: step2
        run: |
          #Convert json to powershell
          $json_object = "${{steps.step1.outputs.TESTURL }}" | ConvertFrom-Json

          #Use jq to extract the value
          $key_value=$json_object."test-url"

          #Print the retrieved value
          echo "retrieved value: $key_value"
          
