name: Capture JSON Output Example

on:
   workflow_dispatch:
jobs:
  capture_json:
    runs-on: windows-latest

    steps:
      - name: Generate JSON output
        id: generate_json
        run: |
          $timestamp=$(date --utc +%Y-%m-%dT%H:%M:%SZ)
          # Generate some JSON output using a shell command
          $json_output=$(echo '{"name": "John Doe", "age": 30, "datetime": $timestamp}')
          
          # Output the JSON to the console (just for logging)
          echo "Generated JSON: $json_output"
          
          # Save the JSON output to a file using tee
          echo "$json_output" | tee output.json

          # Set the JSON output as an environment variable for later steps
          echo "JSON_OUTPUT=$json_output" >> $GITHUB_ENV

      - name: Process JSON output in a subsequent step
        run: |
          # Read the JSON from the environment variable and use jq to parse it
          echo "Processing JSON..."
          
          # Example of using jq to extract values from the JSON
          $name=$(echo "$JSON_OUTPUT" | jq -r '.name')
          $age=$(echo "$JSON_OUTPUT" | jq -r '.age')
          $datetime=$(echo "$JSON_OUTPUT" | jq -r '.datetime')

          # Display extracted values
          echo "Name: $name"
          echo "Age: $age"
          echo "Is Admin: $datetime"
